
worker_processes  1;

events {
    worker_connections  10000;
}

http {
        gzip on;
        gzip_types text/plain application/xml text/css application/json application/javascript;
        gzip_min_length 1000;

        upstream todo {
            server app:8000; #need to same an gunicorn bind
            }

        server {
            listen 80;
            server_name 13.201.22.144 justcode.co.in;  # Replace with your domain/IP

            client_max_body_size 100M;

            access_log /var/log/nginx/todo_access.log;
            error_log /var/log/nginx/todo_error.log;

            # Static files (no cache busting for now, adjust as needed)
            #location /static/ {
            #alias /home/ubuntu/myproject/todo/static/;
            #}

            # Media uploads
            #location /media/ {
            #alias /home/ubuntu/myproject/todo/media/;
            #}

            # Proxy to Gunicorn
            location / {
                proxy_pass http://todo;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_redirect off;
            }
        }
        server {
            if ($host = justcode.co.in) {
                return 301 https://$host$request_uri;
            } # managed by Certbot
        }
}