
worker_processes  1;

events {
    worker_connections  10000;
}

http {
        gzip on;
        gzip_types text/plain application/xml text/css application/json application/javascript;
        gzip_min_length 1000;

        upstream todo {
            server app:8000;
        }

        server {
            listen 80;
            server_name justcode.co.in www.justcode.co.in;

            location /.well-known/acme-challenge/ {
                root /var/www/html;
            }

            location / {
                return 301 https://$host$request_uri;
            }
        }

        server {
            listen 443 ssl;
            server_name justcode.co.in www.justcode.co.in;

            ssl_certificate /etc/letsencrypt/live/justcode.co.in/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/justcode.co.in/privkey.pem;

            ssl_protocols TLSv1.2 TLSv1.3;

            location / {
                proxy_pass http://todo;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
            }
        }


}