
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:app/todo
    image: app:todo_app
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10
    restart: unless-stopped

  nginx:
    build: todo/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    image: nginx:latest
    links:
      - app
    restart: unless-stopped
