version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/todo_app
    image: app:todo_app
    container_name: todo_app_container
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10

  nginx:
    build: todo/nginx
    ports:
      - "80:80"
    image: nginx:latest
    links:
      - app
