# Generated by Django 6.0.5 on 2026-05-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
